name: biff

channels:
  - astropy
  - asmeurer

dependencies:
  - python>=3
  - astropy
  - astropy-helpers
  - numpy
  - cython
  - matplotlib
  - scipy
  - pyyaml
  - gsl=1.16
  - pip:
      - astro-gala
